typography_spectrum: 0.8845327
color:
  brandColors:
    - '#FFFFFF'
    - '#8E8E8E'
    - '#16140F'
    - '#4CD964'
    - '#F28877'
  brandStrength: 0.5902256
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Ayr
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Melissa Ayr
    id: 270bb3c2-ee3a-4d8c-8538-91ed86844bdf
    type: content
favicon: null
title: Ayr
purpose: []
